### ISSUE TITLE
TODO: Make these more useful/Connected

### ISSUE THREAD

**Issue by toxicscientist** [toxicscientist/Better-Robotop#1]
What it says on the tin. This is meant to be a list of useful Robotop commands that could help anyone but currently it's a pile of commands stolen from random people. Please reply if you can help/have anything to add.

**Comment by hexagon8899** [comment]
its not stolen if its got permission

**Comment by toxicscientist** [comment]
This was way too vague, I'll make many more specific issues and then compile them into a project
